In [3]:
import numpy as np

In [6]:
a = np.array([[2,3,4],[5,6,7]])
b = np.array([[12,23,34],[15,62,75]])


*Matrix addition*

In [7]:
a.shape

(2, 3)

In [8]:
if(a.shape == b.shape):
  sum = a+b
print(sum)

[[14 26 38]
 [20 68 82]]


In [9]:
# creating random matrices
mat_1 = np.random.randint(10,size = (3,4))
mat_2 = np.random.randint(20,size = (3,4))

In [10]:
mat_1

array([[3, 3, 4, 7],
       [7, 2, 1, 2],
       [5, 9, 0, 3]])

In [11]:
mat_2

array([[ 1,  2,  1,  7],
       [ 5,  7,  3,  2],
       [13,  7, 14,  0]])

In [12]:
sum = np.add(mat_1,mat_2)
sum

array([[ 4,  5,  5, 14],
       [12,  9,  4,  4],
       [18, 16, 14,  3]])

Matrix Subtraction

In [17]:
diff = np.subtract(a,b)
diff

array([[-10, -20, -30],
       [-10, -56, -68]])

In [16]:
diff1 = mat_1 - mat_2
diff1

array([[  2,   1,   3,   0],
       [  2,  -5,  -2,   0],
       [ -8,   2, -14,   3]])

Multiplication of matrices

In [18]:
x= 5
mat = np.random.randint(20,size = (3,4))
mat

array([[17,  3,  5, 17],
       [ 5, 18,  4,  1],
       [ 1,  4,  8,  4]])

In [19]:
product = np.multiply(x,mat)
product

array([[85, 15, 25, 85],
       [25, 90, 20,  5],
       [ 5, 20, 40, 20]])

In [20]:
product = np.dot(a,b)

ValueError: ignored

In [21]:
# creating random matrices
mat_3 = np.random.randint(10,size = (3,4))
mat_4 = np.random.randint(20,size = (4,4))
product1 = np.dot(mat_3,mat_4)
product1

array([[309, 312, 315, 303],
       [146, 157, 123, 138],
       [164, 215, 235, 122]])

Element wise multiplication

In [23]:
# creating random matrices
mat_5 = np.random.randint(10,size = (3,3))
mat_6 = np.random.randint(20,size = (3,3))
mul = np.multiply(mat_5,mat_6)

In [25]:
print(mat_5)
print(mat_6)

[[9 4 8]
 [1 1 5]
 [4 6 1]]
[[12  8  8]
 [ 6 10  1]
 [ 7 14  5]]


In [26]:
mul

array([[108,  32,  64],
       [  6,  10,   5],
       [ 28,  84,   5]])